[package]
name = "rustyminesweeper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
crossterm = "0.27"
gtk = "0.18"
gio = "0.18"

[lib]
name = "lib"
path = "src/lib.rs"
